from __future__ import annotations

# NOAA GHCN station identifiers use FIPS 10-4 country prefixes rather than
# ISO-3166 codes.  Keep the names aligned with the country names exposed by
# the GUI and map only countries present in NOAA's GHCN country catalogue.
COUNTRY_FIPS_CODES: dict[str, str] = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "AG",
    "Angola": "AO",
    "Antigua and Barbuda": "AC",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AS",
    "Austria": "AU",
    "Azerbaijan": "AJ",
    "Bahamas": "BF",
    "Bahrain": "BA",
    "Bangladesh": "BG",
    "Barbados": "BB",
    "Belarus": "BO",
    "Belgium": "BE",
    "Belize": "BH",
    "Benin": "BN",
    "Bolivia": "BL",
    "Bosnia and Herzegovina": "BK",
    "Botswana": "BC",
    "Brazil": "BR",
    "Brunei": "BX",
    "Bulgaria": "BU",
    "Burkina Faso": "UV",
    "Burundi": "BY",
    "Cabo Verde": "CV",
    "Cambodia": "CB",
    "Cameroon": "CM",
    "Canada": "CA",
    "Central African Republic": "CT",
    "Chad": "CD",
    "Chile": "CI",
    "China": "CH",
    "Colombia": "CO",
    "Congo": "CF",
    "Costa Rica": "CS",
    "Cote d'Ivoire": "IV",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czechia": "EZ",
    "Democratic Republic of the Congo": "CG",
    "Denmark": "DA",
    "Dominica": "DO",
    "Dominican Republic": "DR",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "ES",
    "Equatorial Guinea": "EK",
    "Eritrea": "ER",
    "Estonia": "EN",
    "Eswatini": "WZ",
    "Ethiopia": "ET",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GB",
    "Gambia": "GA",
    "Georgia": "GG",
    "Germany": "GM",
    "Ghana": "GH",
    "Greece": "GR",
    "Guatemala": "GT",
    "Guinea": "GV",
    "Guinea-Bissau": "PU",
    "Guyana": "GY",
    "Honduras": "HO",
    "Hungary": "HU",
    "Iceland": "IC",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IZ",
    "Ireland": "EI",
    "Israel": "IS",
    "Italy": "IT",
    "Jamaica": "JM",
    "Japan": "JA",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KR",
    "Kuwait": "KU",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LG",
    "Lebanon": "LE",
    "Lesotho": "LT",
    "Liberia": "LI",
    "Libya": "LY",
    "Lithuania": "LH",
    "Luxembourg": "LU",
    "Madagascar": "MA",
    "Malawi": "MI",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "RM",
    "Mauritania": "MR",
    "Mauritius": "MP",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Mongolia": "MG",
    "Montenegro": "MJ",
    "Morocco": "MO",
    "Mozambique": "MZ",
    "Myanmar": "BM",
    "Namibia": "WA",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NU",
    "Niger": "NG",
    "Nigeria": "NI",
    "North Korea": "KN",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Oman": "MU",
    "Pakistan": "PK",
    "Palau": "PS",
    "Panama": "PM",
    "Papua New Guinea": "PP",
    "Paraguay": "PA",
    "Peru": "PE",
    "Philippines": "RP",
    "Poland": "PL",
    "Portugal": "PO",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RS",
    "Rwanda": "RW",
    "Saint Lucia": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SG",
    "Serbia": "RI",
    "Seychelles": "SE",
    "Sierra Leone": "SL",
    "Singapore": "SN",
    "Slovakia": "LO",
    "Slovenia": "SI",
    "Solomon Islands": "BP",
    "South Africa": "SF",
    "South Korea": "KS",
    "Spain": "SP",
    "Sri Lanka": "CE",
    "Sudan": "SU",
    "Suriname": "NS",
    "Sweden": "SW",
    "Switzerland": "SZ",
    "Syria": "SY",
    "Tajikistan": "TI",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Togo": "TO",
    "Tonga": "TN",
    "Trinidad and Tobago": "TD",
    "Tunisia": "TS",
    "Turkey": "TU",
    "Turkmenistan": "TX",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UP",
    "United Arab Emirates": "AE",
    "United Kingdom": "UK",
    "USA": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "NH",
    "Venezuela": "VE",
    "Vietnam": "VM",
    "Zambia": "ZA",
    "Zimbabwe": "ZI",
}

COUNTRY_CODE_MAP: dict[str, str] = {code: name for name, code in COUNTRY_FIPS_CODES.items()}

_COUNTRY_ALIASES: dict[str, str] = {
    "czech republic": "Czechia",
    "deutschland": "Germany",
    "great britain": "United Kingdom",
    "korea, north": "North Korea",
    "korea, south": "South Korea",
    "polska": "Poland",
    "republic of the congo": "Congo",
    "swaziland": "Eswatini",
    "the bahamas": "Bahamas",
    "the gambia": "Gambia",
    "united states": "USA",
    "united states of america": "USA",
    "uk": "United Kingdom",
    "us": "USA",
}


def normalize_country_name(value: str) -> str:
    normalized = " ".join(value.strip().split())
    if not normalized:
        raise ValueError("country is required")

    alias = _COUNTRY_ALIASES.get(normalized.casefold())
    if alias is not None:
        return alias

    for country_name in COUNTRY_FIPS_CODES:
        if country_name.casefold() == normalized.casefold():
            return country_name
    raise ValueError(f"Country is not available in the NOAA GHCN catalogue: {normalized}")


def country_to_fips_code(value: str) -> str:
    stripped = value.strip().upper()
    if len(stripped) == 2 and stripped in COUNTRY_CODE_MAP:
        return stripped
    return COUNTRY_FIPS_CODES[normalize_country_name(value)]
